<?php

namespace SymfonyDay\Bundle\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getMostRecentPosts()
    {
        return $this
            ->createQueryBuilder('p')
            ->where('p.publishedAt IS NULL')
            ->orWhere('p.publishedAt <= :date')
            ->orderBy('p.publishedAt', 'DESC')
            ->setParameter('date', date('Y-m-d H:i'))
            ->getQuery()
            ->execute()
        ;
    }
}